import Image from "next/image";

export default function PhotoGrid() {
  return (
    <>
      <Image
        id="img-1"
        src={"/images/woman.jpeg"}
        alt="An image generated by Minertia"
        width={280}
        height={280}
        loading="lazy"
      />
      <Image
        id="img-2"
        src={"/images/man.jpeg"}
        alt="An image generated by Minertia"
        width={280}
        height={280}
        loading="lazy"
      />
      <Image
        id="img-3"
        src={"/images/running-horses.jpeg"}
        alt="An image generated by Minertia"
        width={280}
        height={280}
        loading="lazy"
      />
      <Image
        id="img-4"
        src={"/images/car-city.jpeg"}
        alt="An image generated by Minertia"
        width={280}
        height={280}
        loading="lazy"
      />
    </>
  );
}
